version: "3"

services:
        app:
                build:
                        context: .
                ports:
                        - "8000:8000"
                volumes:
                        - ./app:/app
                command: >
                        sh -c "python manage.py wait_for_db &&
                               python manage.py migrate &&
                               python manage.py runserver 0.0.0.0:8000"
                environment:
                        - DB_HOST=db
                        - DB_NAME=app
                        - DB_USER=postgres
                        - DB_PASS=supersecretpassword
                depends_on:
                        - db
                        - elasticsearch

        db:
                image: postgres:10-alpine
                environment:
                        - POSTGRES_DB=app
                        - POSTGRES_USER=postgres
                        - POSTGRES_PASSWORD=supersecretpassword

        elasticsearch:
                image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
                container_name: elasticsearch
                restart: always
                environment:
                    - xpack.security.enabled=false
                    - discovery.type=single-node
                ulimits:
                    memlock:
                        soft: -1
                        hard: -1
                    nofile:
                        soft: 65536
                        hard: 65536
                cap_add:
                    - IPC_LOCK
                volumes:
                    - elasticsearch-data:/usr/share/elasticsearch/data
                ports:
                    - 9200:9200

volumes:
    elasticsearch-data:
        driver: local
